import {toggleAudio} from './audio';
import {outfits,stages,locations,readSave,persist,purchase,upgrade,sale,type Look} from './game';
export function mountGame(change:(look:Look)=>Promise<boolean>,finishShow:()=>Promise<boolean>,photo:()=>Promise<Blob|null>=async()=>null,view:(mode:string)=>void=()=>{},ready:()=>boolean=()=>true,selectPlace:(id:string)=>boolean=()=>true){
 const state=readSave();let music=false;let busy=false,tab='wardrobe',lastSale='Покупатели ждут новую коллекцию.',showRunning=false;
 const panel=document.querySelector<HTMLElement>('#panel')!;
 const money=(v:number)=>Math.round(v).toLocaleString('ru-RU')+' ₣';
 function save(){if(!persist(state))notify('Safari не разрешил сохранить прогресс. Не закрывайте вкладку.');}
 function notify(text:string){let el=document.querySelector<HTMLElement>('#toast');if(!el){el=document.createElement('div');el.id='toast';el.role='status';document.body.append(el);}el.textContent=text;el.hidden=false;setTimeout(()=>{el!.hidden=true;},4500);}
 async function wear(look:Look){if(busy||showRunning)return;busy=true;draw();try{const ok=await change(look);if(ok){state.look={...look};save();}else notify('Не удалось применить образ. Проверьте загрузку персонажа и повторите.');}catch{notify('Ошибка смены образа. Попробуйте ещё раз.');}finally{busy=false;draw();}}
 function draw(){
 panel.innerHTML=`<div class="balance">${money(state.money)}</div><p>${stages[state.level][0]} · ${state.sales} продаж · ${state.shows} показов</p><div class="row"><button id="music">${music?"Музыка: вкл.":"Музыка: выкл."}</button><button id="photo">Сделать фото</button></div><nav><button data-tab="appearance" class="${tab==='appearance'?'active':''}">Модель</button><button data-tab="wardrobe" class="${tab==='wardrobe'?'active':''}">Гардероб</button><button data-tab="business" class="${tab==='business'?'active':''}">Бизнес</button><button data-tab="career" class="${tab==='career'?'active':''}">Карьера</button><button data-tab="locations" class="${tab==='locations'?'active':''}">Локации</button></nav>`;
 if(tab==='wardrobe')panel.innerHTML+=`${outfits.map(o=>`<div class="card"><b>${o.name}</b><p>${o.description}</p><button data-outfit="${o.id}" ${busy?'disabled':''}>${state.owned.includes(o.id)?(state.look.outfit===o.id?'Надето':'Надеть'):'Купить · '+money(o.price)}</button></div>`).join('')}<div class="field"><label for="color">Цвет ткани</label><input id="color" type="color" value="${state.look.color}"></div><div class="field"><label for="shine">Блеск</label><input id="shine" type="range" min="0" max="92" value="${Math.round((1-state.look.roughness)*100)}"></div><div class="row"><button data-fabric="satin">Сатин</button><button data-fabric="leather">Кожа</button><button data-fabric="chrome">Металлик</button></div><button id="favorite">Сохранить комплект</button>${state.favorites.map((_,i)=>`<button data-favorite="${i}">Комплект ${i+1}</button>`).join('')}`;
 if(tab==='appearance')panel.innerHTML+=`<div class="card"><b>Взрослые модели</b><p>Елена — длинные волосы. Майя — короткое каре и другая форма лица.</p><div class="row"><button data-persona="elena" ${busy||showRunning?'disabled':''}>Елена</button><button data-persona="maya" ${busy||showRunning?'disabled':''}>Майя</button></div></div>${[['height','Рост',.9,1.1,.01,1],['waist','Талия',-1,1,.05,0],['hips','Бёдра',0,2,.05,0],['bust','Грудь',0,2,.05,0]].map(([id,label,min,max,step,fallback])=>`<div class="field"><label for="shape-${id}">${label} <output id="value-${id}">${id==='height'?Math.round((state.look.height??1)*175)+' см':Math.round((state.look[id as 'waist']??0)*100)+'%'}</output></label><input id="shape-${id}" data-shape="${id}" ${!ready()||busy||showRunning?'disabled':''} type="range" min="${min}" max="${max}" step="${step}" value="${state.look[id as 'height']??fallback}"></div>`).join('')}<div class="row"><button data-view="full">Полный рост</button><button data-view="face">Портрет</button><button data-view="side">Сбоку</button></div><p>${ready()?'Настройки активны. Одежда меняется вместе с телом.':'Настройки станут доступны после успешной загрузки 3D.'} Сохраните образ в гардеробе.</p>`;
 if(tab==='business'){const next=stages[state.level+1];panel.innerHTML+=`<div class="card"><b>Продажи коллекции</b><p>Одна продажа каждые 12 секунд, пока игра открыта. Выручка минус ткань и зарплаты — ваша прибыль.</p><p id="sale-status">${lastSale}</p><button id="sell">Обслужить клиента</button></div><div class="card"><b>${next?next[0]:'Империя построена'}</b><p>${next?'Новая локация увеличит выручку.':'Достигнут последний этап.'}</p>${next?`<button id="upgrade">Открыть · ${money(next[1])}</button>`:''}</div><div class="card"><b>Сотрудники: ${state.staff}</b><p>Каждый сотрудник увеличивает выручку на 15 ₣ и расходы на 7 ₣ за продажу.</p><button id="hire">Нанять · ${money(350+state.staff*150)}</button></div>`;}
 if(tab==='locations')panel.innerHTML+=`<p>Новые интерьеры открываются при развитии бизнеса.</p>${locations.map(l=>`<div class="card"><b>${l.name}</b><p>${l.level>state.level?'Откроется на этапе «'+stages[l.level][0]+'».':state.location===l.id?'Выбранный интерьер':'Доступный интерьер'}</p><button data-location="${l.id}" ${l.level>state.level||showRunning?'disabled':''}>${state.location===l.id?'Выбрано':'Перейти'}</button></div>`).join('')}`;
 if(tab==='career')panel.innerHTML+=`<div class="card"><b>Показ новой коллекции</b><p>Модель пройдёт по подиуму и примет позу. Награда зависит от коллекции и развития бренда.</p><button id="show" ${showRunning||busy?'disabled':''}>${showRunning?'Показ идёт…':'Начать показ · 80 ₣'}</button></div><button id="daily">Ежедневная награда · 200 ₣</button><div class="card"><b>Достижения</b><p>${state.sales>=5?'✓':'○'} Первые 5 продаж</p><p>${state.owned.length===3?'✓':'○'} Три коллекции</p><p>${state.shows>=3?'✓':'○'} Три показа</p><p>${state.level>=3?'✓':'○'} Собственный дом моды</p></div><p>Прогресс сохраняется на этом устройстве.</p>`;
 panel.querySelectorAll<HTMLButtonElement>('[data-location]').forEach(b=>b.onclick=()=>{const id=b.dataset.location!;if(!locations.some(l=>l.id===id&&l.level<=state.level)||showRunning)return;if(!selectPlace(id)){notify('3D-интерьер пока недоступен. Дождитесь загрузки сцены.');return;}state.location=id;save();draw();notify('Интерьер изменён');});
 panel.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view!));
 panel.querySelectorAll<HTMLButtonElement>('[data-persona]').forEach(b=>b.onclick=()=>void wear({...state.look,persona:b.dataset.persona!}));
 panel.querySelectorAll<HTMLInputElement>('[data-shape]').forEach(input=>{const update=()=>{if(busy||showRunning||!ready())return;const name=input.dataset.shape!;const previous=state.look[name as 'height']??(name==='height'?1:0);const value=Number(input.value),look={...state.look,[name]:value};const output=panel.querySelector<HTMLOutputElement>('#value-'+name);void change(look).then(ok=>{if(ok){state.look=look;save();if(output)output.value=name==='height'?Math.round(value*175)+' см':Math.round(value*100)+'%';}else{input.value=String(previous);notify('Дождитесь загрузки персонажа.');}}).catch(()=>{input.value=String(previous);notify('Не удалось изменить фигуру. Попробуйте снова.');});};input.oninput=update;input.onchange=update;});
 on('music',async()=>{music=await toggleAudio();draw();});
 on('photo',async()=>{let blob:Blob|null=null;try{blob=await photo();}catch{notify('Не удалось сделать фото. Попробуйте снова.');return;}if(!blob){notify('Дождитесь загрузки 3D-персонажа');return;}const url=URL.createObjectURL(blob);const dialog=document.createElement('dialog');dialog.className='photo-dialog';dialog.innerHTML=`<h2>Ваша фотосессия</h2><img alt="Фотография вашего 3D-образа" src="${url}"><div class="row"><a download="Luxury-Fashion-Empire.png" href="${url}">Скачать фото</a><button id="share-photo">Поделиться</button><button id="close-photo">Закрыть</button></div>`;document.body.append(dialog);dialog.showModal();dialog.querySelector('#close-photo')!.addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{URL.revokeObjectURL(url);dialog.remove();});dialog.querySelector('#share-photo')!.addEventListener('click',async()=>{const file=new File([blob],'Luxury-Fashion-Empire.png',{type:'image/png'});try{if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'Мой образ Luxury Fashion Empire'});else notify('Нажмите «Скачать фото»');}catch{notify('Публикация фото отменена');}});});
 panel.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab!;draw();});
 panel.querySelectorAll<HTMLButtonElement>('[data-outfit]').forEach(b=>b.onclick=()=>{const id=b.dataset.outfit!;if(!state.owned.includes(id)){if(!purchase(state,id)){notify('Недостаточно денег. Продайте коллекцию.');return;}save();}void wear({...state.look,outfit:id});});
 const input=panel.querySelector<HTMLInputElement>('#color');if(input)input.oninput=()=>{state.look.color=input.value;void change(state.look);save();};
 const shine=panel.querySelector<HTMLInputElement>('#shine');if(shine)shine.oninput=()=>{state.look.roughness=1-Number(shine.value)/100;void change(state.look);save();};
 panel.querySelectorAll<HTMLButtonElement>('[data-fabric]').forEach(b=>b.onclick=()=>{const kind=b.dataset.fabric;state.look.roughness=kind==='leather'?.16:kind==='chrome'?.12:.42;state.look.metalness=kind==='chrome'?.75:.08;void change(state.look);save();draw();});
 panel.querySelectorAll<HTMLButtonElement>('[data-favorite]').forEach(b=>b.onclick=()=>void wear(state.favorites[Number(b.dataset.favorite)]));
 on('favorite',()=>{state.favorites.push({...state.look});state.favorites=state.favorites.slice(-6);save();notify('Комплект сохранён');draw();});
 on('upgrade',()=>{if(showRunning){notify('Дождитесь окончания показа');return;}if(!upgrade(state))notify('Недостаточно денег');else{save();selectPlace(state.location);notify('Открыто: '+stages[state.level][0]);draw();}});
 on('hire',()=>{const cost=350+state.staff*150;if(state.money<cost){notify('Недостаточно денег');return;}state.money-=cost;state.staff++;save();draw();});
 on('sell',()=>{if(Date.now()-manualSale<4000){notify('Клиент ещё выбирает. Подождите немного.');return;}manualSale=Date.now();processSale();});
 on('daily',()=>{const day=new Date().toLocaleDateString('sv-SE');if(state.daily===day){notify('Сегодня награда уже получена');return;}state.daily=day;state.money+=200;save();draw();notify('+200 ₣');});
 on('show',async ()=>{if(state.money<80){notify('На организацию нужно 80 ₣');return;}state.money-=80;showRunning=true;save();draw();let completed=false;try{completed=await finishShow();}catch{completed=false;}if(!completed){state.money+=80;showRunning=false;save();draw();notify('Сначала дождитесь загрузки персонажа');return;}state.shows++;const rating=Math.min(99,68+state.owned.length*5+state.level*2);const reward=180+rating*2+state.level*30;state.money+=reward;state.earned+=reward;showRunning=false;save();draw();notify(`Показ: ${rating}/100. Приз ${money(reward)}`);});
 }
 function on(id:string,fn:()=>void){const b=panel.querySelector<HTMLButtonElement>('#'+id);if(b)b.onclick=fn;}
 let manualSale=0;
 function processSale(){const result=sale(state);lastSale=`Выручка ${money(result.revenue)} − расходы ${money(result.cost)} = прибыль ${money(result.profit)}`;save();
 if(tab==='business'){const el=document.querySelector('#sale-status');if(el)el.textContent=lastSale;}const balance=panel.querySelector('.balance');if(balance)balance.textContent=money(state.money);}
 setInterval(()=>{if(!document.hidden&&!busy)processSale();},12000);
 draw();return {initialLook:state.look,initialLocation:state.location,refresh:draw};
}
